from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.security import APIKeyHeader
import stripe
import uuid

app = FastAPI()

# In-memory storage for valid keys generated by Stripe
VALID_KEYS = set()

apiKeyHeader = APIKeyHeader(name="X-API-Key", auto_error=False)

@app.post("/webhook/stripe")
async def stripe_webhook(request: Request):
    payload = await request.body()
    # Handle Stripe checkout.session.completed
    new_key = f"sk_live_{uuid.uuid4().hex}"
    VALID_KEYS.add(new_key)
    print(f"=== NEW GENERATED API KEY: {new_key} ===", flush=True)
    return {"status": "success", "key": new_key}

@app.get("/permits")
def get_permits(x_api_key: str = Header(None)):
    if not x_api_key or x_api_key not in VALID_KEYS:
        raise HTTPException(status_code=401, detail="Invalid or missing API Key")
    return {"permits": [{"id": 1, "type": "Building", "status": "Approved"}]}
    
    